### ISSUE TITLE
Tremor not logging any error when a Kafka offramp fails to start

### ISSUE THREAD

**Issue by anuprout** [wayfair-tremor/tremor-runtime#77] opened 2020-02-27 19:43 UTC
**Problem**
Hi, It was observed that Tremor is not logging any error when a Kafka offramp is failed to start. In my case, there was a syntactical error in Kafka offramp config where I was not using string format for one of the **rdkafka_options**. As a result the underlying Kafka producers could not be started . However Tremor didn't throw any error while the service was started. 

**Steps**

1. Create an off ramp with below config.
```
offramp:
- id: kafka
  type: kafka
  metrics_interval_s: 10
  codec: influx
  config:
    brokers:
    - <some broker host:port>
   topic: <some topic>
    rdkafka_options:
      enable.idempotence: true
      **max.in.flight.requests.per.connection: 5**  ## pass in Integer format
```

2. start Tremor service & verify the service status 
3. Check Tremor log

**Possible Solution(s)**

1. Please see if the error handing can be implemented in such cases.
2. It would also be great if Tremor can refactor the formats before passing to "rdkafka". 

**Notes**
```
tremor-runtime:0.6.0
rd_kafka version: 1.2.1
```

(edit by @Licenser to add code blocks for readability)

**Comment by Licenser** [comment] 2020-02-27 19:44
Good catch thanks!

**Comment by Licenser** [comment] 2020-03-03 14:39
I can't reproduce this.

`max.in.flight.requests.per.connection: 5` is a valid configuration and gets passed correctly.

Addin a bad config like `max.in.flight.requests.per.connection: snot` will result in an error:

```
[2020-03-03T14:38:32Z ERROR tremor_server] error: Client config error: Invalid value for configuration property "max.in.flight.requests.per.connection" max.in.flight.requests.per.connection snot
error: Client config error: Invalid value for configuration property "max.in.flight.requests.per.connection" max.in.flight.requests.per.connection snot
```

Can you elaborate on the issue?

**Comment by Licenser** [comment] 2020-03-03 14:48
I confirmed that the configuration works:

![image](https://user-images.githubusercontent.com/119093/75787060-70e00b80-5d66-11ea-9690-a6f09d99c2da.png)

**Comment by Licenser** [comment] 2020-03-12 14:09
@anuprout can we close this issue or do you have a way to reproduce the error you originally saw?

**Comment by Licenser** [comment] 2020-04-07 19:19
Closing for now, feel free to reopen tie issue if it persists.

**Closed by Licenser** 2020-04-07 19:19 UTC
Labels: bug, can not reproduce
