### ISSUE TITLE
Combine tremor-query and tremor-script into tremor-tool

### ISSUE THREAD

**Issue by darach** [wayfair-tremor/tremor-runtime#148] opened 2020-04-02 14:01 UTC
**Describe the problem you are trying to solve**

Currently the docker file does not package tremor-query nor tremor-script
binaries - these would be useful to assist folk who are learning tremor via the
docker image

**Describe the solution you'd like**

Add to the dockerized images.

**Notes**

Document invoking the tools via `docker run` + `docker exec` against a running container

**Comment by Licenser** [comment] 2020-04-02 14:08
We already ship tremor-tool. Since we want to consolidate on that perhaps we can prioritize on that so people don't get sad when tremor-query / tremor-script go away?

**Comment by darach** [comment] 2020-04-02 14:11
Yes, that's the implementation I had in mind - its high time we merged all those together into a single better tool!

**Comment by Licenser** [comment] 2020-04-16 14:07
renaming this to reflect the intend.

**Comment by Licenser** [comment] 2020-04-16 14:14
closing as a duplicate of #8 and #7

**Closed by Licenser** 2020-04-16 14:14 UTC
Labels: duplicate, enhancement
